<a href="https://colab.research.google.com/github/monicassilva/especialista-ia-alura-santander/blob/main/05_ia_aplicada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Módulo 5

In [ ]:
import numpy as np

# Definindo os dados para as colunas
nomes_produtos = [f"Produto {i+1}" for i in range(50)]
categorias_produtos = np.random.choice(["Eletrônicos", "Livros", "Roupas", "Alimentos", "Brinquedos"], 50)
precos_produtos = np.random.uniform(10.0, 500.0, 50).round(2)
itens_vendidos = np.random.randint(1, 1000, 50)
avaliacoes_produtos = np.random.uniform(1.0, 5.0, 50).round(1)

# Criando o DataFrame
df_produtos = pd.DataFrame({
    "Nome do produto": nomes_produtos,
    "Categoria do produto": categorias_produtos,
    "Preço do produto": precos_produtos,
    "Itens vendidos": itens_vendidos,
    "Avaliação do produto": avaliacoes_produtos
})

# Exibindo as primeiras linhas do DataFrame
df_produtos.head()

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
0,Produto 1,Eletrônicos,115.95,340,3.4
1,Produto 2,Eletrônicos,432.65,952,1.8
2,Produto 3,Brinquedos,181.80,112,4.7
3,Produto 4,Eletrônicos,381.18,863,3.5
4,Produto 5,Alimentos,342.91,70,5.0

In [ ]:
df_produtos["Categoria do produto"]

0     Eletrônicos
1     Eletrônicos
2      Brinquedos
3     Eletrônicos
4       Alimentos
5          Livros
6      Brinquedos
7      Brinquedos
8          Roupas
9     Eletrônicos
10     Brinquedos
11     Brinquedos
12      Alimentos
13     Brinquedos
14     Brinquedos
15    Eletrônicos
16     Brinquedos
17      Alimentos
18      Alimentos
19         Livros
20      Alimentos
21     Brinquedos
22      Alimentos
23         Roupas
24      Alimentos
25         Livros
26      Alimentos
27         Livros
28         Roupas
29         Livros
30      Alimentos
31         Roupas
32         Livros
33    Eletrônicos
34      Alimentos
35      Alimentos
36      Alimentos
37    Eletrônicos
38     Brinquedos
39         Roupas
40     Brinquedos
41         Livros
42      Alimentos
43         Livros
44         Livros
45    Eletrônicos
46         Roupas
47         Livros
48     Brinquedos
49         Roupas
Name: Categoria do produto, dtype: object

In [ ]:
df_produtos["Categoria do produto"].unique()

array(['Eletrônicos', 'Brinquedos', 'Alimentos', 'Livros', 'Roupas'],
      dtype=object)

In [ ]:
set(df_produtos["Categoria do produto"])

{'Alimentos', 'Brinquedos', 'Eletrônicos', 'Livros', 'Roupas'}

### Filtrando elementos de um Dataframe Pandas

In [ ]:
df_produtos[df_produtos["Categoria do produto"] == "Eletrônicos"]

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
0,Produto 1,Eletrônicos,115.95,340,3.4
1,Produto 2,Eletrônicos,432.65,952,1.8
3,Produto 4,Eletrônicos,381.18,863,3.5
9,Produto 10,Eletrônicos,345.39,241,1.5
15,Produto 16,Eletrônicos,377.58,89,3.9
33,Produto 34,Eletrônicos,322.29,771,1.7
37,Produto 38,Eletrônicos,12.89,763,2.7
45,Produto 46,Eletrônicos,50.80,165,4.3

In [ ]:
df_produtos_filtro_avaliacao_menor_que_2 = df_produtos[df_produtos["Avaliação do produto"] < 2.0]
df_produtos_filtro_avaliacao_menor_que_2

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
1,Produto 2,Eletrônicos,432.65,952,1.8
9,Produto 10,Eletrônicos,345.39,241,1.5
11,Produto 12,Brinquedos,433.22,218,1.3
14,Produto 15,Brinquedos,84.13,846,1.9
19,Produto 20,Livros,420.75,144,1.1
22,Produto 23,Alimentos,406.63,528,1.9
26,Produto 27,Alimentos,138.88,703,1.3
30,Produto 31,Alimentos,441.86,596,1.6
33,Produto 34,Eletrônicos,322.29,771,1.7
42,Produto 43,Alimentos,305.20,358,1.1

In [ ]:
df_produtos.shape

(50, 5)

In [ ]:
df_produtos_filtro_avaliacao_menor_que_2.shape

(10, 5)

In [ ]:
df_produtos[(df_produtos["Categoria do produto"] == "Eletrônicos") & (df_produtos["Preço do produto"] >= 350.0)]

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
1,Produto 2,Eletrônicos,432.65,952,1.8
3,Produto 4,Eletrônicos,381.18,863,3.5
15,Produto 16,Eletrônicos,377.58,89,3.9

In [ ]:
df_produtos.iloc[15]

Nome do produto          Produto 16
Categoria do produto    Eletrônicos
Preço do produto             377.58
Itens vendidos                   89
Avaliação do produto            3.9
Name: 15, dtype: object

In [ ]:
df_produtos.iloc[34:42]

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
34,Produto 35,Alimentos,36.82,787,3.4
35,Produto 36,Alimentos,462.33,301,3.5
36,Produto 37,Alimentos,399.00,205,2.9
37,Produto 38,Eletrônicos,12.89,763,2.7
38,Produto 39,Brinquedos,404.78,287,3.5
39,Produto 40,Roupas,455.64,963,3.1
40,Produto 41,Brinquedos,90.56,600,2.5
41,Produto 42,Livros,379.90,393,4.5

In [ ]:
df_produtos.iloc[43:]

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
43,Produto 44,Livros,482.40,693,2.3
44,Produto 45,Livros,233.39,42,2.0
45,Produto 46,Eletrônicos,50.80,165,4.3
46,Produto 47,Roupas,77.22,51,2.2
47,Produto 48,Livros,224.41,686,3.2
48,Produto 49,Brinquedos,210.84,760,3.6
49,Produto 50,Roupas,214.58,365,3.8

In [ ]:
df_produtos_com_indice = df_produtos.set_index("Nome do produto")
df_produtos_com_indice

,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
Nome do produto,,,,
Produto 1,Eletrônicos,115.95,340,3.4
Produto 2,Eletrônicos,432.65,952,1.8
Produto 3,Brinquedos,181.80,112,4.7
Produto 4,Eletrônicos,381.18,863,3.5
Produto 5,Alimentos,342.91,70,5.0
Produto 6,Livros,436.58,174,3.5
Produto 7,Brinquedos,188.78,820,4.0
Produto 8,Brinquedos,444.68,479,3.4
Produto 9,Roupas,331.82,404,3.9
Produto 10,Eletrônicos,345.39,241,1.5
Produto 11,Brinquedos,234.39,160,2.3
Produto 12,Brinquedos,433.22,218,1.3
Produto 13,Alimentos,208.99,428,2.4
Produto 14,Brinquedos,436.83,58,4.5
Produto 15,Brinquedos,84.13,846,1.9
Produto 16,Eletrônicos,377.58,89,3.9
Produto 17,Brinquedos,68.64,543,2.4
Produto 18,Alimentos,341.69,42,2.1
Produto 19,Alimentos,211.39,122,2.6
Produto 20,Livros,420.75,144,1.1
Produto 21,Alimentos,249.40,726,4.2
Produto 22,Brinquedos,157.45,132,4.3
Produto 23,Alimentos,406.63,528,1.9
Produto 24,Roupas,187.59,57,2.8
Produto 25,Alimentos,129.95,411,2.0
Produto 26,Livros,47.80,37,3.0
Produto 27,Alimentos,138.88,703,1.3
Produto 28,Livros,138.01,443,3.2
Produto 29,Roupas,313.65,126,4.6
Produto 30,Livros,438.28,507,2.1
Produto 31,Alimentos,441.86,596,1.6
Produto 32,Roupas,480.44,426,3.5
Produto 33,Livros,388.36,311,4.8
Produto 34,Eletrônicos,322.29,771,1.7
Produto 35,Alimentos,36.82,787,3.4
Produto 36,Alimentos,462.33,301,3.5
Produto 37,Alimentos,399.00,205,2.9
Produto 38,Eletrônicos,12.89,763,2.7
Produto 39,Brinquedos,404.78,287,3.5
Produto 40,Roupas,455.64,963,3.1
Produto 41,Brinquedos,90.56,600,2.5
Produto 42,Livros,379.90,393,4.5
Produto 43,Alimentos,305.20,358,1.1
Produto 44,Livros,482.40,693,2.3
Produto 45,Livros,233.39,42,2.0
Produto 46,Eletrônicos,50.80,165,4.3
Produto 47,Roupas,77.22,51,2.2
Produto 48,Livros,224.41,686,3.2
Produto 49,Brinquedos,210.84,760,3.6
Produto 50,Roupas,214.58,365,3.8

In [ ]:
df_produtos_com_indice.loc["Produto 15"]

Categoria do produto    Brinquedos
Preço do produto             84.13
Itens vendidos                 846
Avaliação do produto           1.9
Name: Produto 15, dtype: object

In [ ]:
df_produtos_com_indice.loc["Produto 15":"Produto 20"]

,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
Nome do produto,,,,
Produto 15,Brinquedos,84.13,846,1.9
Produto 16,Eletrônicos,377.58,89,3.9
Produto 17,Brinquedos,68.64,543,2.4
Produto 18,Alimentos,341.69,42,2.1
Produto 19,Alimentos,211.39,122,2.6
Produto 20,Livros,420.75,144,1.1

In [ ]:
df_produtos_com_indice.loc["Produto 45":]

,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
Nome do produto,,,,
Produto 45,Livros,233.39,42,2.0
Produto 46,Eletrônicos,50.80,165,4.3
Produto 47,Roupas,77.22,51,2.2
Produto 48,Livros,224.41,686,3.2
Produto 49,Brinquedos,210.84,760,3.6
Produto 50,Roupas,214.58,365,3.8

In [ ]:
df_produtos_com_indice.loc["Produto 45", "Itens vendidos"]

np.int64(42)

In [ ]:
df_produtos_com_indice.loc[["Produto 45", "Produto 47", "Produto 16"], ["Preço do produto", "Itens vendidos"]]

                 Preço do produto  Itens vendidos
Nome do produto
Produto 45                 233.39              42
Produto 47                  77.22              51
Produto 16                 377.58              89

In [ ]:
eletronicos = df_produtos_com_indice[df_produtos_com_indice["Categoria do produto"] == "Eletrônicos"]
df_produtos_com_indice.loc[eletronicos.index, ["Preço do produto", "Itens vendidos"]]

                 Preço do produto  Itens vendidos
Nome do produto
Produto 1                  115.95             340
Produto 2                  432.65             952
Produto 4                  381.18             863
Produto 10                 345.39             241
Produto 16                 377.58              89
Produto 34                 322.29             771
Produto 38                  12.89             763
Produto 46                  50.80             165

In [ ]:
brinquedos = df_produtos_com_indice[df_produtos_com_indice["Categoria do produto"] == "Brinquedos"]
df_produtos_com_indice.loc[brinquedos.index, "Categoria do produto"] = "Infanto-juvenil"

In [ ]:
brinquedos

,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
Nome do produto,,,,
Produto 3,Brinquedos,181.80,112,4.7
Produto 7,Brinquedos,188.78,820,4.0
Produto 8,Brinquedos,444.68,479,3.4
Produto 11,Brinquedos,234.39,160,2.3
Produto 12,Brinquedos,433.22,218,1.3
Produto 14,Brinquedos,436.83,58,4.5
Produto 15,Brinquedos,84.13,846,1.9
Produto 17,Brinquedos,68.64,543,2.4
Produto 22,Brinquedos,157.45,132,4.3
Produto 39,Brinquedos,404.78,287,3.5
Produto 41,Brinquedos,90.56,600,2.5
Produto 49,Brinquedos,210.84,760,3.6

In [ ]:
df_produtos_com_indice

,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
Nome do produto,,,,
Produto 1,Eletrônicos,115.95,340,3.4
Produto 2,Eletrônicos,432.65,952,1.8
Produto 3,Infanto-juvenil,181.80,112,4.7
Produto 4,Eletrônicos,381.18,863,3.5
Produto 5,Alimentos,342.91,70,5.0
Produto 6,Livros,436.58,174,3.5
Produto 7,Infanto-juvenil,188.78,820,4.0
Produto 8,Infanto-juvenil,444.68,479,3.4
Produto 9,Roupas,331.82,404,3.9
Produto 10,Eletrônicos,345.39,241,1.5
Produto 11,Infanto-juvenil,234.39,160,2.3
Produto 12,Infanto-juvenil,433.22,218,1.3
Produto 13,Alimentos,208.99,428,2.4
Produto 14,Infanto-juvenil,436.83,58,4.5
Produto 15,Infanto-juvenil,84.13,846,1.9
Produto 16,Eletrônicos,377.58,89,3.9
Produto 17,Infanto-juvenil,68.64,543,2.4
Produto 18,Alimentos,341.69,42,2.1
Produto 19,Alimentos,211.39,122,2.6
Produto 20,Livros,420.75,144,1.1
Produto 21,Alimentos,249.40,726,4.2
Produto 22,Infanto-juvenil,157.45,132,4.3
Produto 23,Alimentos,406.63,528,1.9
Produto 24,Roupas,187.59,57,2.8
Produto 25,Alimentos,129.95,411,2.0
Produto 26,Livros,47.80,37,3.0
Produto 27,Alimentos,138.88,703,1.3
Produto 28,Livros,138.01,443,3.2
Produto 29,Roupas,313.65,126,4.6
Produto 30,Livros,438.28,507,2.1
Produto 31,Alimentos,441.86,596,1.6
Produto 32,Roupas,480.44,426,3.5
Produto 33,Livros,388.36,311,4.8
Produto 34,Eletrônicos,322.29,771,1.7
Produto 35,Alimentos,36.82,787,3.4
Produto 36,Alimentos,462.33,301,3.5
Produto 37,Alimentos,399.00,205,2.9
Produto 38,Eletrônicos,12.89,763,2.7
Produto 39,Infanto-juvenil,404.78,287,3.5
Produto 40,Roupas,455.64,963,3.1
Produto 41,Infanto-juvenil,90.56,600,2.5
Produto 42,Livros,379.90,393,4.5
Produto 43,Alimentos,305.20,358,1.1
Produto 44,Livros,482.40,693,2.3
Produto 45,Livros,233.39,42,2.0
Produto 46,Eletrônicos,50.80,165,4.3
Produto 47,Roupas,77.22,51,2.2
Produto 48,Livros,224.41,686,3.2
Produto 49,Infanto-juvenil,210.84,760,3.6
Produto 50,Roupas,214.58,365,3.8

In [ ]:
df_produtos_com_indice['Categoria do produto'].unique()

array(['Eletrônicos', 'Infanto-juvenil', 'Alimentos', 'Livros', 'Roupas'],
      dtype=object)

Desafio:
1. Carregar um arquivo .csv com feedback de clientes (reviews.csv)
2. Usar um LLM para classificar o sentimento de cada feedback (Positivo, Negativo, Neutro)
3. Adicionar uma nova coluna com essa classificação ao DataFrame.

In [ ]:
# Etapa 1
df_reviews = pd.read_csv("/content/reviews.csv")

In [ ]:
df_reviews.head()

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0

In [ ]:
coluna_de_reviews = df_reviews["reviewText"]
coluna_de_reviews

0     it works as expected. I should have sprung for...
1     This think has worked out great.Had a diff. br...
2     Bought it with Retail Packaging, arrived legit...
3     It's mini storage.  It doesn't do anything els...
4     I have it in my phone and it never skips a bea...
5     It works, but file writes are a bit slower tha...
6     I bought 2 of those SanDisk 32 GB microSD , us...
7     The memory card is an excellent condition and ...
8     I bougth this micro SD card after some trubles...
9     Ordered this for a Galaxy S3.  Lasted a few mo...
10    more like 8mb/s in my Note 10.1 and that's usi...
11    I used this for a few months in my phone, then...
12    everything about it was great, except for the ...
13    Used in my phone it's plenty fast and works ju...
14    This card advertises itself as UHS1 but it's a...
15    I bought this SD card for my android phone thi...
16    good card. work as describes. haven't had any ...
17    I got this because I just couldn't pass up the...
18    It works but the actual R/W speeds are 18/8 MB...
19    Does it's job and fairly cheap for what it's w...
20    Still don't feel is very fast or is just my ph...
21    I bought 64GB version of the card to use with ...
22    I have an old SanDisk SD card that still works...
23    Used it in my Galaxy Note 2 for the past 16 mo...
24    Worked great in my galaxy s4--until it didn't ...
25    I bought this on August of 2013.  As of April ...
26    So this product is a large disappointment...bo...
27    I will keep it short and sweet for potential b...
28    The package arrived on time, it's very well pa...
29    Does what it says. Hasn't broken yet, and I ho...
30    Thus microSD card worked fine for a year in my...
31    I think this is probably a fine product, but i...
32    I have two of these and use them for my Galazy...
33    I join the long list of customers who have had...
34    I do not get the advertised speed of 30MB/s, m...
35    the micro sd works great as described. but bew...
36    than i expected. I don't know if it would kill...
37    Reliable and inexpensive. However, it's quite ...
38    I bought this primarily to use in my Surface P...
39    I really don't know what to think about this I...
Name: reviewText, dtype: object

### Few-shot prompting

In [ ]:
# Etapa 2
lista_de_analises_de_sentimentos = []

for review_numero, resenha in enumerate(coluna_de_reviews):
    resposta = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=f"""Você irá analisar a resenha que eu te mandarei abaixo, e retorna com uma análise de sentimento.
                    Você deve responder APENAS com uma das seguintes palavras: 'Positiva', 'Negativa' ou 'Neutra',
                    indicando o sentimento relativo àquela resenha específica.

                    Exemplos:
                    'Eu adorei esse produto' -> Positiva
                    'Gostei, mas não é nada de especial' -> Neutra
                    'Odiei esse produto' -> Negativa

                    Segue a resenha a ser analisada: {resenha}
                    """
    )
    lista_de_analises_de_sentimentos.append(resposta.text)
    print(f"Resenha {review_numero}: '{resenha}' -> Sentimento: {resposta.text}")

Resenha 0: 'it works as expected. I should have sprung for the higher capacity.  I think its made a bit cheesier than the earlier versions; the paint looks not as clean as before' -> Sentimento: Negativa
Resenha 1: 'This think has worked out great.Had a diff. bran 64gb card and if went south after 3 months.This one has held up pretty well since I had my S3, now on my Note3.*** update 3/21/14I've had this for a few months and have had ZERO issue's since it was transferred from my S3 to my Note3 and into a note2. This card is reliable and solid!Cheers!' -> Sentimento: Positiva
Resenha 2: 'Bought it with Retail Packaging, arrived legit, in a orange envelope, english version not asian like the picture shows. arrived quickly, bought a 32 and 16 both retail packaging for my htc one sv and Lg Optimus, both cards in working order, probably best price you'll get for a nice sd card' -> Sentimento: Positiva
Resenha 3: 'It's mini storage.  It doesn't do anything else and it's not supposed to.  I purchased it to add additional storage to my Microsoft Surface Pro tablet which only come in 64 and 128 GB.  It does what it's supposed to and SanDisk has a long standing reputation that speaks for itself.' -> Sentimento: Positiva
Resenha 4: 'I have it in my phone and it never skips a beat. File transfers are speedy and have not had any corruption issues or memory fade issues as I would expect from the Sandisk brand. Great card to own. Why entrust your precious files to a slightly cheaper piece of crap? If you lose everything can you forgive yourself for not spending the extra couple bucks on a trusted product that goes through good QA?' -> Sentimento: Positiva
Resenha 5: 'It works, but file writes are a bit slower than expected on a USB3 reader.Also, both reads and writes are FASTER with the card inside the standard-size SD adapter (15 MB/s vs 10 write; 45 MB/s vs 22 MB/s read) on the same card reader.  Can't figure why...' -> Sentimento: Negativa
Resenha 6: 'I bought 2 of those SanDisk 32 GB microSD , used them on my Galaxy Note and Galaxy S4First one , my phone started saying it was removed , then recognize it again :) then diedI thought it's just a luck , plugged in the 2nd one :) stayed for about 2 months and died suddenly ! and lost everythingnever buying from SanDisk again .. ever' -> Sentimento: Negativa
Resenha 7: 'The memory card is an excellent condition and work as described. Dependable and easy to use. An excellent choice for the enthusiast who requires more storage.' -> Sentimento: Positiva
Resenha 8: 'I bougth this micro SD card after some trubles with other that i got from Kingston, i can tell that SanDisk is other quality, this is the best, my i9300 phone can read a 64GB very fast, the dta transfer speed from my pc to my is amazing, if you are looking for additional storage to you phone, for music, pictures and other type of files, this is for you.Pros-Very good quality materials of construction-Amazing speedUpdate after one year this memory is damaged I can not delete or put new files on it, I can not format this memory, I tried to format with my phone, with my pc, with a camera and nothing, now this is like a 64gb cd, the data in the memory is only available to read but I can not move, or delete it, I bought this memory to be used to backup all my data of my android device but now is only a readable memory I can not write data on it any more, I hope sandisk make a better products in the future!!! Total disagree I will buy a Samsung memory card expected a better quality.' -> Sentimento: Negativa
Resenha 9: 'Ordered this for a Galaxy S3.  Lasted a few months and then broke.  Is not accessible on several different PC's.Says "limited lifetime" warranty - BS.  You have ONE MONTH for Eco Zone.  Not only did I lose pictures but now I am out $$ because of a crappy return policy.In the future I will be buying Kingston, not Sandisk.-----------------Update:  Amazon Customer service made good and refunded my purchase price.  I still will not be buying any more Sandisk memory cards however...' -> Sentimento: Negativa
Resenha 10: 'more like 8mb/s in my Note 10.1 and that's using SanDisk's own app. A bit faster in my Note II, but still a disappointment for devices with quad core processors. Not sure if it's the card or the device, so benefit of the doubt and four stars.' -> Sentimento: Positiva
Resenha 11: 'I used this for a few months in my phone, then it decided to quit mounting. I lost some pictures of pets who died shortly after. I got a replacement card, but I had to send in the old one, giving up any chance of recovering its contents. The new one's worked fine, but failing after 3 months in inexcusable.' -> Sentimento: Negativa
Resenha 12: 'everything about it was great, except for the adapter.  It was to tight i had to use a tool to take it back out of the adapter causing me to chip it. so my fault i guess, but i also bought a 16gb version and the adapter for that one was fine.' -> Sentimento: Negativa
Resenha 13: 'Used in my phone it's plenty fast and works just like it should. Unexpectedly comes with mini and full SD card size adapters, which is nice. &#34;Fool-proof&#34; packaging or whatever it was, that was laughable. Packaging was decent it just shouldn't have bragged about being impossible to mess up when I messed it up.' -> Sentimento: Positiva
Resenha 14: 'This card advertises itself as UHS1 but it's actually UHS50.This means that it will not go up to SDR104 speeds/throughput.Not necessary bad, just false advertising.' -> Sentimento: Negativa
Resenha 15: 'I bought this SD card for my android phone thinking that a class 10 will be faster and more reliable than others. it turns out, the difference in class doesn't really matter at least for Android phones. didn't really worth the price difference' -> Sentimento: Negativa
Resenha 16: 'good card. work as describes. haven't had any issue with it or going pass metal detectors. no lost files or missing files.' -> Sentimento: Positiva
Resenha 17: 'I got this because I just couldn't pass up the deal, $17.99. It has been incredibly fast in my HTC Sensation 4g. Pictures are taken and saved instantaneously. Only had it a few days, but have been very happy. Shipping was fast and the packaging was easy to open which is always great in my book. Only issue I had was I had to format it on my computer first before my phone was able to recognize it.' -> Sentimento: Positiva
Resenha 18: 'It works but the actual R/W speeds are 18/8 MB/s, not even Class 10. It should be marketed as "Sandisk Basic", not Sandisk Ultra", unless they mean ultra slow. Now is 2014 and there is no excuse for such slow card from Sandisk.*** UPDATE ***I have redone the test with NotePro 12.2" instead of using non UHS-I PC and the latest results are 32/8.6MB/s. Since the read speed hits 30, I believe the device is DHS-I ready. Still underwhelmed by the write speed though.' -> Sentimento: Negativa
Resenha 19: 'Does it's job and fairly cheap for what it's worth. I had to return my first one and exchange it for another because the first one was defective. Sandisk really needs to do better quality assurance on their products. The second one works perfectly fine. I use it for my GoPro camera.' -> Sentimento: Neutra
Resenha 20: 'Still don't feel is very fast or is just my phone, I guess I will need to remove it and run some R/W tests. Still Its ok.' -> Sentimento: Neutra
Resenha 21: 'I bought 64GB version of the card to use with GoPro Hero 3 black edition.  It didn't work out.  The card worked OK if camera was set to resolution with lower bit rates.  E.g. worked fine in 720p with protune on, or 1080p with protune off.  However, in 1080p with protune on (bitrate is just shy of 6 MB/s in this mode -- much higher then with protune turned off) it was nothing but trouble.  Camera would sometime work, and sometime randomly stop recording for no obvious reason.  I first suspected camera, but testing with different SD cards, it ended up being SanDisk's card that was at fault.  My spare card, an old and cheap 16GB PNY (also class 10), worked just fine under same conditions and with same camera settings.Once it was obvious it was problem with the card, I found people on GoPro's forums that had trouble with this specific card as well (well, you always find these only after you figure it out for yourself, right?).  Anyhow, I did some speed tests with the card by doing simple write of 1GB file full of zeros using Unix dd utility to copy 1GB of zeros from /dev/zero (where else would you find that many zeros ;-) onto a file on the card.  The result was that on average, SanDisk's card would manage about 10.2 MB/s.  Just barely above the bar for class 10 card.  However, that was average over 1GB.  During the write test, the speed was oscillating with many spikes and drops.  Drops were as low as 7MB/s.  Uh.  I thought write speed of class 10 card should never dip below 10 MB/s?  For comparison, my old cheap class 10 PNY card was chugging along at constant 13 MB/s under the same test.  No spikes and no drops in speed.The card will probably work fine in most devices, as bitrates when recording 1080p video are often low enough and/or camera might have huge buffer.  But if you want to use it to record video at high bitrates, and your device doesn't have huge buffer to compensate for speed bumps of this card, you may run into trouble.  Be wary of using it in Hero3 in modes that have higher bit rates (e.g. 1080p with protune enabled).SanDisk's website lists part numbers as SDSDQUI-064G with adapter, and SDSDQUA-064G without adapter.  This conflicts with product description on Amazon.  While this is likely just Amazon not getting product description right again (a bit too common thing), it's interesting to note.[Update Apr 20 2013]:Some numbers from testing the card.  The test is extremely simple.  Write out 1GB of zeros onto the card using standard Unix dd command to read 128KB blocks of zeroes from special device /dev/zero and write it onto the card.  128KB * 8192 = 1GB.  dd displays transfer stats once it finishes.  While dd was running, I run iostat in second terminal displaying 1 second interval stats as a measure of current speed.  This was done on the Mac.  dd command line can be used as-is to repeat test on Linux system, however iostat command is different on Linux and would need to be modified slightly.  I choose 128KB block size, as that seems to be what device drivers merges sequential writes into anyhow.  Using different block sizes, results are comparable.$ dd if=/dev/zero of=test bs=131072 count=81928192+0 records in8192+0 records out1073741824 bytes transferred in 101.578307 secs (10570582 bytes/sec)So, 10 MB/s and all is good? Right? Wrong! iostat running in parallel with above dd command recorded this:$ iostat -d -w 1 disk2disk2KB/t tps MB/s123.11 76 9.12116.61 185 21.04122.94 49 5.88128.00 41 5.12128.00 89 11.11128.00 134 16.73128.00 69 8.61128.00 61 7.62128.00 99 12.36[ ... and so on until dd finishes writing 1GB of zeros to the card ... ]IMO, the last column should never dip under 10MB/s for card labeled class-10.For comparison, same test run against Samsung Pro 64GB micro-SD card:$ dd if=/dev/zero of=test bs=131072 count=81928192+0 records in8192+0 records out1073741824 bytes transferred in 52.869111 secs (20309436 bytes/sec)$ iostat -d -w 1 disk2disk2KB/t tps MB/s125.30 138 16.86117.73 157 18.03123.04 150 18.00128.00 159 19.86128.00 156 19.47126.45 160 19.73128.00 150 18.72128.00 154 19.22128.00 153 19.11[ ... and so on until dd finishes writing 1GB of zeros to the card ... ]So, Samsung is on average 2x faster, but more importantly it's speed is much more constant.  And critically important, it never dips under 10MB/s.' -> Sentimento: Negativa
Resenha 22: 'I have an old SanDisk SD card that still works. I thought their new cards would be just as reliable, but I was wrong.The microsd card failed yesterday inside my phone. I used the adapter to connect it to my computer, but it wouldn't mount.I bought this directly from Amazon and not a third party vendor, so I know it's genuine SanDisk.' -> Sentimento: Negativa
Resenha 23: 'Used it in my Galaxy Note 2 for the past 16 months. All the sudden it is no longer writable. I tried many ways to reformat the card. Even Windows says format successful but all files remain after I remove and re-insert the card. Since I have private files in the card I'm not able to delete. I do not want to sent it back to SanDisk for replacement.' -> Sentimento: Negativa
Resenha 24: 'Worked great in my galaxy s4--until it didn't work at all for some unknown reason. Used it for about 4 months before it crapped out. BACK UP YOUR DATA WITH ALL THESE THINGS, THOUGH....' -> Sentimento: Negativa
Resenha 25: 'I bought this on August of 2013.  As of April 2014 the card stopped functioning.  It can still be read, but the writing capability is gone.  That's less than one year.  I'm extremely disappointed in the longevity of this card.  My usage of it has been on my Galaxy S4.  I have about 40Gb of data in it.  Guess I'm going to have to look for another card that has a longer lifespan than this one.' -> Sentimento: Negativa
Resenha 26: 'So this product is a large disappointment...bought it to use in my tablet but the card is forever getting corrupted....I've reformatted the card a few times but it's to the point now that even a reformat doesn't work..  Wasted money...don't recommend purchasing.' -> Sentimento: Negativa
Resenha 27: 'I will keep it short and sweet for potential buyers looking for facts and not b.s.I own two of the 32gb size of these cards for about 3 months now. They do work fairly well with cell phones and tablets, yet not so good with cameras, in fact these cards failed to work with my GoPro Hero3 camera and the customer service rep from Gopro claimed (and I happen to agree with him) that this card is not a true class 10 card let alone UHS-1.Benchmarks with my evo 4g with all allocation sizes the write speed never passed beyond 8mb/s while read speeds wondered around 25mb/s far below advertised speeds, well write speeds arent technically advertised (probably because they are of class 4 level)Benchmarks with crystal mark reported speeds even lower (due to adapter) with write speeds around 6mb/s while read speeds wondered around 20mb/s.Needless to say, if you are not worried about speeds and only about storage, these are perfect. If you want to use them for shooting high definition raw footage however, I suggest you not to loose your money on this, because even if your write speeds are around 10mb/s as the card begins to decay it will slow down to become useless.Again this review is based on GoPro camera and high definition raw recording.. For cell phones or for storage it works perfectly well with a bit of false advertisement..' -> Sentimento: Negativa
Resenha 28: 'The package arrived on time, it's very well packed and it's got an adapter. It works perfectly with my phone, though it doesn't allow a computer format, once it's been on the phone, so it asks you to erase everything before you use it on a computer. So if you're planning on buying this for different purposes and devices, gotta be aware of this. I just need for my phone, so I transfer files with my usb cable, that works just right. I also give it a 3 star because it says there are 64gb, but even when it's totally formatted it only reaches to 60gb..sooo, I don't know where my other 4 gb are...anyways, overall it's working well. I do think it's expensive for what it is.' -> Sentimento: Neutra
Resenha 29: 'Does what it says. Hasn't broken yet, and I hope it doesn't break. I've had luck with this brand before. Usually get bored with the product before it breaks.' -> Sentimento: Positiva
Resenha 30: 'Thus microSD card worked fine for a year in my Samsumg Note II. I mostly used it to listed to downloaded music from Spotify. It has actually failed &#34;twice&#34;. When it failed the first time (the phone couldn't &#34;see&#34; that I had a card installed) I thought maybe something had merely corrupted it, so I formatted it, put it back in my phone, and re-downloaded all my playlists. It worked for two months and then failed again. I don't plan to try formatting it again, I'll switch to a different brand of card.' -> Sentimento: Negativa
Resenha 31: 'I think this is probably a fine product, but it wasn't compatible with my Samsung Galaxy S3 phone. Formatted as exFAT (as it came from the factory), didn't work at all, but that's a known problem with the GS3. But even after reformatting to FAT32, the card caused my phone to reboot multiple times.' -> Sentimento: Negativa
Resenha 32: 'I have two of these and use them for my Galazy Note 2. It's great having the flexibility to keep extra storage with you for your 'phablet'.So far they have done what they are intended to do.' -> Sentimento: Positiva
Resenha 33: 'I join the long list of customers who have had their SanDisk die on them.  Customer service from SanDisk has been helpful.  They pay for UPS shipping for the return and promise a 7-10 day turn around once the defective disk has been returned.  Still it's a pain to deal with and I lost some photographs.UPDATE: SanDisk sent me a replacement and it seems to be working.  If the replacement goes bad, I'll be back to complain:)SECOND UPDATE: All is well with the replacement so I'm giving it three stars.' -> Sentimento: Neutra
Resenha 34: 'I do not get the advertised speed of 30MB/s, more like a 200-300KB/s on my Galaxy S4. At least it gives me a lot of extra storage space, for a phone it works nicely if you don't need to transfer big files.' -> Sentimento: Negativa
Resenha 35: 'the micro sd works great as described. but beware that the micro sd adapters are faulty. the micro sd will get stuck in the adapter. you will have to carefully rip apart the adapter to get the micro sd out thus damaging the apapter.' -> Sentimento: Negativa
Resenha 36: 'than i expected. I don't know if it would kill any manufacturers to actually have a memory card or stick or device to actually HAVE Available the advertised capacity. Fortunately l learned that the advertised and actual available memory are TWO SEPARATE THINGS before i bought it, always scroll down and read the technical spec of a device or anything before you buy as that way ideally, your actually informed. Let the buyer beware, is more appropriate every day as most things are not exactly as they seem. And if it's food and cheap, it's likely cancer causing and don't feed your body and your car in the same place.' -> Sentimento: Negativa
Resenha 37: 'Reliable and inexpensive. However, it's quite slow, far, far slower than the 64GB samsung pro microsdxc. The Samsung works well for interactive use while I would only use this Sandisk card for applications where speed isn't important.' -> Sentimento: Negativa
Resenha 38: 'I bought this primarily to use in my Surface Pro. It would randomly dismount itself. I do not know if it was the Surface's fault or the card's fault. Upon doing a little internet searching, I found this to be a common problem with Sandisk cards and the Surface Pro. I used another brand microSDXC and it has worked fine.' -> Sentimento: Negativa
Resenha 39: 'I really don't know what to think about this I got it thinking it would solve my memory problems but that's not the case turns out you can only put certain things on this and of course none of the thingsthat are eating up your memory on.your will go there is a way to swap your internal memory for your external card but it's not easy and you have to root  your phone' -> Sentimento: Negativa

In [ ]:
lista_de_analises_de_sentimentos

['Negativa',
 'Positiva',
 'Positiva',
 'Positiva',
 'Positiva',
 'Negativa',
 'Negativa',
 'Positiva',
 'Negativa',
 'Negativa',
 'Positiva',
 'Negativa',
 'Negativa',
 'Positiva',
 'Negativa',
 'Negativa',
 'Positiva',
 'Positiva',
 'Negativa',
 'Neutra',
 'Neutra',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Neutra',
 'Positiva',
 'Negativa',
 'Negativa',
 'Positiva',
 'Neutra',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa']

In [ ]:
# Etapa 3
df_reviews["Análises de Sentimentos"] = lista_de_analises_de_sentimentos

In [ ]:
df_reviews

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,Análises de Sentimentos
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0,Negativa
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0,Positiva
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0,Positiva
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0,Positiva
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0,Positiva
5,A2Q3ICGWZLY3JJ,B007WTAJTO,98020,"It works, but file writes are a bit slower tha...",1384905600,20/11/2013,383,0,0,Negativa
6,AF24M1HKIZ7QC,B007WTAJTO,"Abdulrahman J. Alrashed ""dr34m3r""","I bought 2 of those SanDisk 32 GB microSD , us...",1375488000,08/03/2013,640,0,0,Negativa
7,A1KIF9Z5VFPH7H,B007WTAJTO,"Abel Feliciano ""Ace Master""",The memory card is an excellent condition and ...,1347321600,09/11/2012,759,0,0,Positiva
8,A1FKE13D77L3Y3,B007WTAJTO,Abraham Arturo Meza Marin,I bougth this micro SD card after some trubles...,1361232000,19/02/2013,657,0,0,Negativa
9,A1X1FX3NSOFCT3,B007WTAJTO,"Abused Commuter ""abused_commuter""",Ordered this for a Galaxy S3. Lasted a few mo...,1374278400,20/07/2013,506,0,1,Negativa
10,A3RV1L35IPTV61,B007WTAJTO,abushaheed,more like 8mb/s in my Note 10.1 and that's usi...,1357430400,01/06/2013,555,0,0,Positiva
11,A2RJ7DAL63MN1F,B007WTAJTO,Ace of Sevens,"I used this for a few months in my phone, then...",1391126400,31/01/2014,311,0,0,Negativa
12,A3IJIFZ5HH819V,B007WTAJTO,A. Cho,"everything about it was great, except for the ...",1373414400,07/10/2013,427,0,0,Negativa
13,A1R0JMNRV7HVQM,B007WTAJTO,ACZ,Used in my phone it's plenty fast and works ju...,1383609600,11/05/2013,576,0,0,Positiva
14,APAEBFIM1588A,B007WTAJTO,"Adam Wright ""Electrical Engineer""",This card advertises itself as UHS1 but it's a...,1378684800,09/09/2013,455,1,1,Negativa
15,A1JOXGZH55JMHW,B007WTAJTO,A. Hejazi,I bought this SD card for my android phone thi...,1386806400,12/12/2013,361,0,0,Negativa
16,A35NR2GQWMQ31K,B007WTAJTO,ahhsimon,good card. work as describes. haven't had any ...,1391644800,02/06/2014,189,0,0,Positiva
17,A1N7LGUPJWWQS9,B007WTAJTO,A.J. Matheson,I got this because I just couldn't pass up the...,1353888000,26/11/2012,742,0,0,Positiva
18,A28CTDM7OP0RAR,B007WTAJTO,Alan,It works but the actual R/W speeds are 18/8 MB...,1395705600,25/03/2014,258,0,0,Negativa
19,A1NA2JGI3GNDN2,B007WTAJTO,Albert,Does it's job and fairly cheap for what it's w...,1399161600,05/04/2014,247,0,0,Neutra
20,A3PCW69GQK8R38,B007WTAJTO,Alejandro Hernndez,Still don't feel is very fast or is just my ph...,1391385600,02/03/2014,281,0,0,Neutra
21,A1UM44ILLZCEI1,B007WTAJTO,Aleksandar Milivojevic,I bought 64GB version of the card to use with ...,1364947200,04/03/2013,644,1,1,Negativa
22,A2T71JNR3C2DY1,B007WTAJTO,"Ali Etezadkhah ""Ali""",I have an old SanDisk SD card that still works...,1371859200,22/06/2013,534,0,0,Negativa
23,A87U7LY9OKZNY,B007WTAJTO,A. Liu,Used it in my Galaxy Note 2 for the past 16 mo...,1398988800,05/02/2014,306,0,0,Negativa
24,A277QWS5WF6DWI,B007WTAJTO,Alton L Spencer,Worked great in my galaxy s4--until it didn't ...,1401148800,27/05/2014,195,0,0,Negativa
25,A1WWPAQ1DD6BQC,B007WTAJTO,A. Marte,I bought this on August of 2013. As of April ...,1403654400,25/06/2014,166,1,1,Negativa
26,A3FY6V3LXP8SSL,B007WTAJTO,"Amazon Customer ""fiction buff""",So this product is a large disappointment...bo...,1349136000,10/02/2012,1032,0,0,Negativa
27,A3DXCQV1U6QLTS,B007WTAJTO,Amazon Customer,I will keep it short and sweet for potential b...,1360195200,02/07/2013,524,0,0,Negativa
28,A3R2TY7PFN9VSM,B007WTAJTO,Amazon Customer,"The package arrived on time, it's very well pa...",1375660800,08/05/2013,579,0,0,Neutra
29,A1FZKP9XTKMALD,B007WTAJTO,Amazon Customer,"Does what it says. Hasn't broken yet, and I ho...",1375401600,08/02/2013,668,0,1,Positiva
30,A308JP3BK4VAL7,B007WTAJTO,Amazon Customer,Thus microSD card worked fine for a year in my...,1398643200,28/04/2014,224,0,3,Negativa
31,A392ZR68AKLDCK,B007WTAJTO,"Amazon Customer ""Music Fan""","I think this is probably a fine product, but i...",1374796800,26/07/2013,500,1,1,Negativa
32,A2DQ2U5BYIXNUJ,B007WTAJTO,"Amazon Customer ""PawsitivelySafe""",I have two of these and use them for my Galazy...,1387152000,16/12/2013,357,0,0,Positiva
33,A14D2PS27PI3FM,B007WTAJTO,Amazon Fan,I join the long list of customers who have had...,1359936000,02/04/2013,615,1,2,Neutra
34,A1Z7FZP81N8CDU,B007WTAJTO,Amazon Shopper,"I do not get the advertised speed of 30MB/s, m...",1394755200,14/03/2014,269,0,1,Negativa
35,A1T8FVB93QQNOM,B007WTAJTO,Andrew M. Swiatek,the micro sd works great as described. but bew...,1372464000,29/06/2013,527,0,0,Negativa
36,A3K1JZPUXSADRJ,B007WTAJTO,anonomous,than i expected. I don't know if it would kill...,1362182400,03/02/2013,673,0,2,Negativa
37,A1D07XDTMWV0A5,B007WTAJTO,"A. Shieh ""eff.org""","Reliable and inexpensive. However, it's quite ...",1385769600,30/11/2013,373,0,0,Negativa
38,A1HKW2TELCHGLL,B007WTAJTO,astraelraen,I bought this primarily to use in my Surface P...,1391040000,30/01/2014,312,0,0,Negativa
39,A3P86Z2D81VLYV,B007WTAJTO,"Zeality ""N2iT""",I really don't know what to think about this I...,1396137600,30/03/2014,253,0,0,Negativa